import type { Session } from './types'

type Language = 'ro' | 'en'

export function exportSessionsText(
  sessions: Session[],
  language: Language,
): string {
  const lines: string[] = []
  const header =
    language === 'ro'
      ? 'Emot-ID — Rezumatul sesiunilor'
      : 'Emot-ID — Session Summary'

  lines.push(header)
  lines.push('='.repeat(header.length))
  lines.push('')

  const locale = language === 'ro' ? 'ro-RO' : 'en-US'
  const dateLabel = language === 'ro' ? 'Exportat' : 'Exported'
  const exportDate = new Date().toLocaleDateString(locale, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
  const sessionCount = language === 'ro' ? 'Total sesiuni' : 'Total sessions'

  lines.push(`${dateLabel}: ${exportDate}`)
  lines.push(`${sessionCount}: ${sessions.length}`)
  lines.push('')

  for (const session of sessions) {
    const date = new Date(session.timestamp)
    const dateStr = date.toLocaleString(locale, {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })

    lines.push(`--- ${dateStr} (${session.modelId}) ---`)

    const emotionNames = session.results.map((r) => {
      const name = r.label[language]
      const strength = r.matchStrength ? ` (${r.matchStrength[language]})` : ''
      return `  ${name}${strength}`
    })
    lines.push(emotionNames.join('\n'))

    if (session.reflectionAnswer) {
      const reflLabel = language === 'ro' ? 'Reflectie' : 'Reflection'
      lines.push(`  ${reflLabel}: ${session.reflectionAnswer}`)
    }

    if (session.crisisTier !== 'none') {
      const crisisLabel =
        language === 'ro' ? 'Nivel de criza' : 'Crisis level'
      lines.push(`  ${crisisLabel}: ${session.crisisTier}`)
    }

    lines.push('')
  }

  const footer =
    language === 'ro'
      ? 'Generat de Emot-ID. Aceste date nu sunt un diagnostic clinic.'
      : 'Generated by Emot-ID. This data is not a clinical diagnosis.'
  lines.push(footer)

  return lines.join('\n')
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    return false
  }
}

export function downloadAsText(text: string, filename: string): void {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
