/**
 * Export session data for therapy or personal use.
 * Generates a human-readable text summary of sessions.
 */
import type { Session } from './types'

type Language = 'ro' | 'en'

/**
 * Generate a human-readable text summary of recent sessions.
 * Framed as "share with your therapist" — non-clinical, empowering.
 */
export function exportSessionsText(sessions: Session[], language: Language): string {
  const lines: string[] = []
  const header = language === 'ro'
    ? 'Emot-ID — Rezumatul sesiunilor'
    : 'Emot-ID — Session Summary'
  lines.push(header)
  lines.push('='.repeat(header.length))
  lines.push('')

  const dateLabel = language === 'ro' ? 'Exportat' : 'Exported'
  lines.push(`${dateLabel}: ${new Date().toLocaleDateString(language === 'ro' ? 'ro-RO' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`)
  lines.push(`${language === 'ro' ? 'Total sesiuni' : 'Total sessions'}: ${sessions.length}`)
  lines.push('')

  for (const session of sessions) {
    const date = new Date(session.timestamp)
    const dateStr = date.toLocaleString(language === 'ro' ? 'ro-RO' : 'en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })

    lines.push(`--- ${dateStr} (${session.modelId}) ---`)

    const emotionNames = session.results.map((r) => {
      const name = r.label[language]
      const strength = r.matchStrength ? ` (${r.matchStrength[language]})` : ''
      return `  ${name}${strength}`
    })
    lines.push(emotionNames.join('\n'))

    if (session.reflectionAnswer) {
      const reflLabel = language === 'ro' ? 'Reflectie' : 'Reflection'
      lines.push(`  ${reflLabel}: ${session.reflectionAnswer}`)
    }

    if (session.crisisTier !== 'none') {
      const crisisLabel = language === 'ro' ? 'Nivel de criza' : 'Crisis level'
      lines.push(`  ${crisisLabel}: ${session.crisisTier}`)
    }

    lines.push('')
  }

  const footer = language === 'ro'
    ? 'Generat de Emot-ID. Aceste date nu sunt un diagnostic clinic.'
    : 'Generated by Emot-ID. This data is not a clinical diagnosis.'
  lines.push(footer)

  return lines.join('\n')
}

/**
 * Copy text to clipboard with fallback.
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    return false
  }
}

/**
 * Download text as a .txt file.
 */
export function downloadAsText(text: string, filename: string): void {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
